# Generated by Django 4.2.1 on 2023-05-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysystem", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="vipid",
        ),
    ]
