# Generated by Django 4.2.1 on 2023-05-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysystem", "0002_remove_users_vipid"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="viptype",
            field=models.BooleanField(
                blank=True, default=0, help_text="会员标识", null=True, verbose_name="会员标识"
            ),
        ),
    ]
